server:
    port: 9000    
      compression:
        enabled: true
        mime-types: text/html,text/css,application/javascript,application/json
services:
    url:  http://localhost:8080/cookies-spring-webmvc/api/